# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-pr-stale: 90
        days-before-pr-close: 91
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        close-pr-label: 'auto-close'
        stale-pr-message: > 
           This pull request has been inactive for 90 days.
           <br/>If you are finished with your changes, don't forget to sign off. See the [contributor guide](https://review.learn.microsoft.com/help/contribute/contribute-how-to-write-pull-request-automation) for instructions.
           <br/>If this PR is inactive for 14 more days, it will be closed automatically. Thank you!
               <br/>
               <br/>SQL Docs Team
           <br/>[Contact Us](mailto:rogue1@microsoft.com)      
           <br/>[contributor guide](https://review.learn.microsoft.com/help/contribute/sql-server-docs-contribute)
        close-pr-message: >
           <br/>This pull request has been inactive for 91 days. At this time, we're closing the PR. 
           <br/>If you decide to continue working on your change, you can reopen the PR and continue working. Thank you!
           <br/>
           <br/>Microsoft Entra Content Team
           <br/>[Contact Us](mailto:apexidcontent@microsoft.com)
